export const options = [
  { value: "Processor", label: "Processor" },
  { value: "Motherboard", label: "Motherboard" },
  { value: "Ram", label: "Ram" },
  { value: "HDD", label: "HDD" },
  { value: "SSD", label: "SSD" },
  { value: "Power Supply", label: "Power Supply" },
  { value: "Graphics Card", label: "Graphics Card" },
  { value: "Chassis", label: "Chassis" },
  { value: "Case Fan", label: "Case Fan" },
  { value: "Laptop", label: "Laptop" },
  { value: "Printer", label: "Printer" },
  { value: "Monitor", label: "Monitor" },
  { value: "Networking", label: "Networking" },
  { value: "UPS", label: "UPS" },
  { value: "Mechanical Keyboard", label: "Mechanical Keyboard" },
  { value: "Gaming Mouse", label: "Gaming Mouse" },
  { value: "Gaming Headset", label: "Gaming Headset" },
  { value: "Mousepad", label: "Mousepad" },
  { value: "Sound System", label: "Sound System" },
  { value: "Gaming Chair", label: "Gaming Chair" },
  { value: "Custom Build", label: "Custom Build" },
];
